/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "C:\\Users\\热心网民 小明\\AppData\\Roaming\\npm\\node_modules\\vuepress\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-54afc71b",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-54afc71b").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-d7b0c048",
    path: "/blog/basics/html.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d7b0c048").then(next)
    },
  },
  {
    name: "v-4ee5ef60",
    path: "/blog/javascript/%E9%97%AE%E9%A2%98.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4ee5ef60").then(next)
    },
  },
  {
    path: "/blog/javascript/问题.html",
    redirect: "/blog/javascript/%E9%97%AE%E9%A2%98.html"
  },
  {
    path: "/blog/javascript/问题.html",
    redirect: "/blog/javascript/%E9%97%AE%E9%A2%98.html"
  },
  {
    name: "v-feba9738",
    path: "/blog/javascript/%E5%9F%BA%E7%A1%80.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-feba9738").then(next)
    },
  },
  {
    path: "/blog/javascript/基础.html",
    redirect: "/blog/javascript/%E5%9F%BA%E7%A1%80.html"
  },
  {
    path: "/blog/javascript/基础.html",
    redirect: "/blog/javascript/%E5%9F%BA%E7%A1%80.html"
  },
  {
    name: "v-b8c4d480",
    path: "/blog/basics/css.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b8c4d480").then(next)
    },
  },
  {
    path: '*',
    component: GlobalLayout
  }
]