/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "Ming's Notebook",
  "description": "记录所学知识",
  "base": "/MingBlog/",
  "headTags": [],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/home.jpg",
        "heroText": "Ming's Notebook",
        "tagline": "Ming的学习簿",
        "actionText": "瞧一瞧",
        "actionLink": "/blog/javascript/基础",
        "features": [
          {
            "title": "学习",
            "details": "学而不思则罔 | 思而不学则殆"
          },
          {
            "title": "记录",
            "details": "记录每一条知识，保存每一份收获"
          },
          {
            "title": "整理",
            "details": "学无止境，学会梳理知识"
          }
        ],
        "footer": "《劝学》不积跬步无以至千里"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-54afc71b",
      "path": "/"
    },
    {
      "title": "JS",
      "frontmatter": {},
      "regularPath": "/blog/javascript/%E5%9F%BA%E7%A1%80.html",
      "relativePath": "blog/javascript/基础.md",
      "key": "v-feba9738",
      "path": "/blog/javascript/%E5%9F%BA%E7%A1%80.html",
      "headers": [
        {
          "level": 2,
          "title": "<script>",
          "slug": "script"
        },
        {
          "level": 3,
          "title": "推迟执行脚本",
          "slug": "推迟执行脚本"
        },
        {
          "level": 3,
          "title": "异步执行脚本",
          "slug": "异步执行脚本"
        },
        {
          "level": 3,
          "title": "动态加载脚本",
          "slug": "动态加载脚本"
        },
        {
          "level": 2,
          "title": "var 声明提升、let 关键字、const 关键字",
          "slug": "var-声明提升、let-关键字、const-关键字"
        },
        {
          "level": 2,
          "title": "数据类型",
          "slug": "数据类型"
        },
        {
          "level": 2,
          "title": "typeof 与 instanceof 区别",
          "slug": "typeof-与-instanceof-区别"
        },
        {
          "level": 2,
          "title": "for in、for of",
          "slug": "for-in、for-of"
        },
        {
          "level": 2,
          "title": "函数传递参数",
          "slug": "函数传递参数"
        },
        {
          "level": 2,
          "title": "执行上下文",
          "slug": "执行上下文"
        },
        {
          "level": 2,
          "title": "标识符查找",
          "slug": "标识符查找"
        },
        {
          "level": 2,
          "title": "原始值包装类型",
          "slug": "原始值包装类型"
        },
        {
          "level": 2,
          "title": "string 常用方法",
          "slug": "string-常用方法"
        },
        {
          "level": 3,
          "title": "slice()、substring()、substr()",
          "slug": "slice-、substring-、substr"
        },
        {
          "level": 3,
          "title": "indexOf()、lastIndexOf()",
          "slug": "indexof-、lastindexof"
        },
        {
          "level": 3,
          "title": "startsWith()、endsWith()、includes()",
          "slug": "startswith-、endswith-、includes"
        },
        {
          "level": 3,
          "title": "trim()",
          "slug": "trim"
        },
        {
          "level": 3,
          "title": "字符串解构",
          "slug": "字符串解构"
        },
        {
          "level": 3,
          "title": "toLowerCase()、toUpperCase()",
          "slug": "tolowercase-、touppercase"
        },
        {
          "level": 3,
          "title": "replace()",
          "slug": "replace"
        },
        {
          "level": 3,
          "title": "split()",
          "slug": "split"
        },
        {
          "level": 2,
          "title": "Math",
          "slug": "math"
        },
        {
          "level": 2,
          "title": "Array 常用方法",
          "slug": "array-常用方法"
        },
        {
          "level": 3,
          "title": "valueOf()",
          "slug": "valueof"
        },
        {
          "level": 3,
          "title": "join()",
          "slug": "join"
        },
        {
          "level": 3,
          "title": "栈方法 push()、pop()",
          "slug": "栈方法-push-、pop"
        },
        {
          "level": 3,
          "title": "队列方法 shift()、unshift()",
          "slug": "队列方法-shift-、unshift"
        },
        {
          "level": 3,
          "title": "排序方法 reverse()、sort()",
          "slug": "排序方法-reverse-、sort"
        },
        {
          "level": 3,
          "title": "concat()",
          "slug": "concat"
        },
        {
          "level": 3,
          "title": "slice()",
          "slug": "slice"
        },
        {
          "level": 3,
          "title": "splice()",
          "slug": "splice"
        },
        {
          "level": 3,
          "title": "indexOf()、lastIndexOf()和 includes()",
          "slug": "indexof-、lastindexof-和-includes"
        },
        {
          "level": 3,
          "title": "find()、findIndex()",
          "slug": "find-、findindex"
        },
        {
          "level": 3,
          "title": "迭代方法 every()、filter()、forEach()、map() 和 some()",
          "slug": "迭代方法-every-、filter-、foreach-、map-和-some"
        },
        {
          "level": 3,
          "title": "归并方法 reduce()、reduceRight()",
          "slug": "归并方法-reduce-、reduceright"
        },
        {
          "level": 2,
          "title": "函数",
          "slug": "函数"
        },
        {
          "level": 3,
          "title": "箭头函数",
          "slug": "箭头函数"
        },
        {
          "level": 3,
          "title": "arguments 对象",
          "slug": "arguments-对象"
        },
        {
          "level": 3,
          "title": "this 对象",
          "slug": "this-对象"
        },
        {
          "level": 3,
          "title": "caller",
          "slug": "caller"
        },
        {
          "level": 3,
          "title": "apply()、call()、bind()",
          "slug": "apply-、call-、bind"
        },
        {
          "level": 2,
          "title": "闭包",
          "slug": "闭包"
        },
        {
          "level": 2,
          "title": "原型",
          "slug": "原型"
        },
        {
          "level": 3,
          "title": "原型层级",
          "slug": "原型层级"
        },
        {
          "level": 3,
          "title": "重写原型",
          "slug": "重写原型"
        },
        {
          "level": 3,
          "title": "继承 原型链",
          "slug": "继承-原型链"
        }
      ]
    },
    {
      "title": "基础语法",
      "frontmatter": {},
      "regularPath": "/blog/vue/%E5%9F%BA%E7%A1%80.html",
      "relativePath": "blog/vue/基础.md",
      "key": "v-f76242b0",
      "path": "/blog/vue/%E5%9F%BA%E7%A1%80.html",
      "headers": [
        {
          "level": 2,
          "title": "hello Vue",
          "slug": "hello-vue"
        },
        {
          "level": 2,
          "title": "指令",
          "slug": "指令"
        },
        {
          "level": 3,
          "title": "文本渲染方法 Mustache语法 v-text v-html",
          "slug": "文本渲染方法-mustache语法-v-text-v-html"
        },
        {
          "level": 3,
          "title": "v-once",
          "slug": "v-once"
        },
        {
          "level": 3,
          "title": "v-if v-else v-else-if",
          "slug": "v-if-v-else-v-else-if"
        },
        {
          "level": 3,
          "title": "v-show",
          "slug": "v-show"
        },
        {
          "level": 3,
          "title": "v-on",
          "slug": "v-on"
        },
        {
          "level": 3,
          "title": "v-bind",
          "slug": "v-bind"
        },
        {
          "level": 3,
          "title": "v-model",
          "slug": "v-model"
        },
        {
          "level": 3,
          "title": "v-for",
          "slug": "v-for"
        },
        {
          "level": 2,
          "title": "计算属性",
          "slug": "计算属性"
        },
        {
          "level": 2,
          "title": "侦听器",
          "slug": "侦听器"
        },
        {
          "level": 2,
          "title": "Vue中的 MVVM",
          "slug": "vue中的-mvvm"
        },
        {
          "level": 2,
          "title": "生命周期",
          "slug": "生命周期"
        },
        {
          "level": 2,
          "title": "Vue 组件",
          "slug": "vue-组件"
        },
        {
          "level": 3,
          "title": "组件名",
          "slug": "组件名"
        },
        {
          "level": 3,
          "title": "全局注册",
          "slug": "全局注册"
        },
        {
          "level": 3,
          "title": "局部注册",
          "slug": "局部注册"
        },
        {
          "level": 3,
          "title": "父子组件传值",
          "slug": "父子组件传值"
        },
        {
          "level": 3,
          "title": "refs 获取",
          "slug": "refs-获取"
        },
        {
          "level": 2,
          "title": "插槽",
          "slug": "插槽"
        },
        {
          "level": 3,
          "title": "默认插槽",
          "slug": "默认插槽"
        },
        {
          "level": 3,
          "title": "具名插槽",
          "slug": "具名插槽"
        },
        {
          "level": 3,
          "title": "作用域插槽",
          "slug": "作用域插槽"
        }
      ]
    },
    {
      "title": "CSS",
      "frontmatter": {},
      "regularPath": "/blog/basics/css.html",
      "relativePath": "blog/basics/css.md",
      "key": "v-b8c4d480",
      "path": "/blog/basics/css.html",
      "headers": [
        {
          "level": 2,
          "title": "position 几个属性的作用",
          "slug": "position-几个属性的作用"
        },
        {
          "level": 2,
          "title": "px，em，rem 的区别",
          "slug": "px-em-rem-的区别"
        },
        {
          "level": 2,
          "title": "怎么让一个不定宽高的 DIV，垂直水平居中",
          "slug": "怎么让一个不定宽高的-div-垂直水平居中"
        },
        {
          "level": 2,
          "title": "CSS实现居中",
          "slug": "css实现居中"
        },
        {
          "level": 3,
          "title": "文字居中",
          "slug": "文字居中"
        },
        {
          "level": 3,
          "title": "图片居中",
          "slug": "图片居中"
        },
        {
          "level": 3,
          "title": "元素居中",
          "slug": "元素居中"
        },
        {
          "level": 2,
          "title": "Flex布局",
          "slug": "flex布局"
        },
        {
          "level": 2,
          "title": "BFC(Block formatting context)",
          "slug": "bfc-block-formatting-context"
        },
        {
          "level": 3,
          "title": "BFC的布局规则",
          "slug": "bfc的布局规则"
        },
        {
          "level": 3,
          "title": "如何创建BFC",
          "slug": "如何创建bfc"
        },
        {
          "level": 3,
          "title": "BFC的作用",
          "slug": "bfc的作用"
        },
        {
          "level": 2,
          "title": "CSS 权重",
          "slug": "css-权重"
        },
        {
          "level": 2,
          "title": "清除浮动的方式",
          "slug": "清除浮动的方式"
        },
        {
          "level": 2,
          "title": "渐进增强和优雅降级",
          "slug": "渐进增强和优雅降级"
        },
        {
          "level": 2,
          "title": "为什么利用多个域名来存储网站资源会更有效",
          "slug": "为什么利用多个域名来存储网站资源会更有效"
        },
        {
          "level": 2,
          "title": "网页的重绘与重排以及重构",
          "slug": "网页的重绘与重排以及重构"
        },
        {
          "level": 2,
          "title": "CSS3 新特性",
          "slug": "css3-新特性"
        },
        {
          "level": 3,
          "title": "CSS3 box-sizing",
          "slug": "css3-box-sizing"
        },
        {
          "level": 3,
          "title": "CSS Grid 网格布局教程",
          "slug": "css-grid-网格布局教程"
        },
        {
          "level": 2,
          "title": "伪类与伪元素",
          "slug": "伪类与伪元素"
        },
        {
          "level": 2,
          "title": "transition（过渡） transform（变换） animation（动画）",
          "slug": "transition-过渡-transform-变换-animation-动画"
        },
        {
          "level": 2,
          "title": "CSS 小细节",
          "slug": "css-小细节"
        },
        {
          "level": 3,
          "title": "CSS 引入的方式",
          "slug": "css-引入的方式"
        },
        {
          "level": 3,
          "title": "块元素和行元素",
          "slug": "块元素和行元素"
        },
        {
          "level": 3,
          "title": "文本省略号",
          "slug": "文本省略号"
        },
        {
          "level": 3,
          "title": "link 和 @import 的区别",
          "slug": "link-和-import-的区别"
        },
        {
          "level": 3,
          "title": "CSS Reset",
          "slug": "css-reset"
        },
        {
          "level": 3,
          "title": "Web 语义化",
          "slug": "web-语义化"
        },
        {
          "level": 3,
          "title": "inline ， block， inline-blockd的区别",
          "slug": "inline-block-inline-blockd的区别"
        },
        {
          "level": 3,
          "title": "display： none；与 visibility： hidden 的区别",
          "slug": "display-none-与-visibility-hidden-的区别"
        },
        {
          "level": 3,
          "title": "CSS Hack",
          "slug": "css-hack"
        },
        {
          "level": 3,
          "title": "overflow 属性值",
          "slug": "overflow-属性值"
        },
        {
          "level": 3,
          "title": "console 常用的方法",
          "slug": "console-常用的方法"
        },
        {
          "level": 3,
          "title": "rgba() 和 opacity 的区别",
          "slug": "rgba-和-opacity-的区别"
        },
        {
          "level": 3,
          "title": "Sass、LESS",
          "slug": "sass、less"
        },
        {
          "level": 3,
          "title": "行内元素、块级元素、空(void)元素、样式之间的转换",
          "slug": "行内元素、块级元素、空-void-元素、样式之间的转换"
        },
        {
          "level": 3,
          "title": "visibility=hidden, opacity=0，display:none",
          "slug": "visibility-hidden-opacity-0-display-none"
        },
        {
          "level": 3,
          "title": "隐藏页面中某个元素的几种方法",
          "slug": "隐藏页面中某个元素的几种方法"
        },
        {
          "level": 3,
          "title": "外边距折叠",
          "slug": "外边距折叠"
        },
        {
          "level": 3,
          "title": "float 的元素，display 是什么",
          "slug": "float-的元素-display-是什么"
        },
        {
          "level": 3,
          "title": "calc 属性",
          "slug": "calc-属性"
        },
        {
          "level": 3,
          "title": "display：table 和 <table>",
          "slug": "display-table-和-table"
        },
        {
          "level": 3,
          "title": "line-height 和 height 的区别",
          "slug": "line-height-和-height-的区别"
        },
        {
          "level": 3,
          "title": "如何不在本身上进行操作，改变一个 DOM 元素的字体颜色",
          "slug": "如何不在本身上进行操作-改变一个-dom-元素的字体颜色"
        },
        {
          "level": 3,
          "title": "设置一个元素的背景颜色，背景颜色会填充哪些区域",
          "slug": "设置一个元素的背景颜色-背景颜色会填充哪些区域"
        }
      ]
    },
    {
      "title": "HTML",
      "frontmatter": {},
      "regularPath": "/blog/basics/html.html",
      "relativePath": "blog/basics/html.md",
      "key": "v-d7b0c048",
      "path": "/blog/basics/html.html",
      "headers": [
        {
          "level": 2,
          "title": "浏览器标准模式和怪异模式",
          "slug": "浏览器标准模式和怪异模式"
        },
        {
          "level": 3,
          "title": "怪异模式",
          "slug": "怪异模式"
        },
        {
          "level": 3,
          "title": "标准模式",
          "slug": "标准模式"
        },
        {
          "level": 2,
          "title": "Doctype 作用",
          "slug": "doctype-作用"
        },
        {
          "level": 2,
          "title": "Label标签",
          "slug": "label标签"
        },
        {
          "level": 3,
          "title": "作用",
          "slug": "作用"
        },
        {
          "level": 3,
          "title": "用法",
          "slug": "用法"
        },
        {
          "level": 2,
          "title": "iframe 是什么、有什么缺点",
          "slug": "iframe-是什么、有什么缺点"
        },
        {
          "level": 2,
          "title": "src 与 href 的区别",
          "slug": "src-与-href-的区别"
        },
        {
          "level": 2,
          "title": "img标签上的title和alt属性的区别",
          "slug": "img标签上的title和alt属性的区别"
        },
        {
          "level": 2,
          "title": "前端页面的三层结构",
          "slug": "前端页面的三层结构"
        },
        {
          "level": 2,
          "title": "div+css 的布局较 table 布局有什么优点",
          "slug": "div-css-的布局较-table-布局有什么优点"
        },
        {
          "level": 2,
          "title": "Canvas 和 SVG 的区别",
          "slug": "canvas-和-svg-的区别"
        },
        {
          "level": 2,
          "title": "viewport",
          "slug": "viewport"
        },
        {
          "level": 3,
          "title": "viewport属性值",
          "slug": "viewport属性值"
        },
        {
          "level": 2,
          "title": "建议 CSS 的<link>标签放在<head>标签之间",
          "slug": "建议-css-的-link-标签放在-head-标签之间"
        },
        {
          "level": 2,
          "title": "建议 JS 的<script>标签放在</body>标签之前",
          "slug": "建议-js-的-script-标签放在-body-标签之前"
        },
        {
          "level": 2,
          "title": "渐进式渲染（progressive rendering）",
          "slug": "渐进式渲染-progressive-rendering"
        },
        {
          "level": 2,
          "title": "DOM 和 BOM",
          "slug": "dom-和-bom"
        },
        {
          "level": 2,
          "title": "DOM Tree 的构建",
          "slug": "dom-tree-的构建"
        },
        {
          "level": 2,
          "title": "前端需要注意的 SEO （搜索引擎优化）",
          "slug": "前端需要注意的-seo-搜索引擎优化"
        },
        {
          "level": 2,
          "title": "浏览器内核的理解",
          "slug": "浏览器内核的理解"
        },
        {
          "level": 2,
          "title": "attribute 和 property 的区别",
          "slug": "attribute-和-property-的区别"
        },
        {
          "level": 2,
          "title": "async 和 defer 的作用和区别",
          "slug": "async-和-defer-的作用和区别"
        },
        {
          "level": 2,
          "title": "image 和 canvas 在处理图片的区别",
          "slug": "image-和-canvas-在处理图片的区别"
        },
        {
          "level": 2,
          "title": "HTML5",
          "slug": "html5"
        },
        {
          "level": 3,
          "title": "HTML5 新特性",
          "slug": "html5-新特性"
        },
        {
          "level": 3,
          "title": "新增的操作 DOM 的方法",
          "slug": "新增的操作-dom-的方法"
        },
        {
          "level": 3,
          "title": "HTML5 本地存储概念",
          "slug": "html5-本地存储概念"
        },
        {
          "level": 3,
          "title": "什么是 Web Worker",
          "slug": "什么是-web-worker"
        },
        {
          "level": 3,
          "title": "HTML5 应用程序缓存和浏览器缓存有什么区别",
          "slug": "html5-应用程序缓存和浏览器缓存有什么区别"
        }
      ]
    },
    {
      "title": "问题",
      "frontmatter": {},
      "regularPath": "/blog/javascript/%E9%97%AE%E9%A2%98.html",
      "relativePath": "blog/javascript/问题.md",
      "key": "v-4ee5ef60",
      "path": "/blog/javascript/%E9%97%AE%E9%A2%98.html",
      "headers": [
        {
          "level": 2,
          "title": "GET请求和POST请求的区别",
          "slug": "get请求和post请求的区别"
        },
        {
          "level": 3,
          "title": "get 请求传参长度的误区",
          "slug": "get-请求传参长度的误区"
        },
        {
          "level": 2,
          "title": "一句话粗略概括闭包",
          "slug": "一句话粗略概括闭包"
        },
        {
          "level": 2,
          "title": "前端中的事件流",
          "slug": "前端中的事件流"
        },
        {
          "level": 2,
          "title": "如何让事件先冒泡后捕获",
          "slug": "如何让事件先冒泡后捕获"
        },
        {
          "level": 2,
          "title": "事件委托",
          "slug": "事件委托"
        },
        {
          "level": 2,
          "title": "图片的懒加载和预加载",
          "slug": "图片的懒加载和预加载"
        },
        {
          "level": 2,
          "title": "mouseover 和 mouseenter 的区别",
          "slug": "mouseover-和-mouseenter-的区别"
        },
        {
          "level": 2,
          "title": "JS 的 new 操作符做了哪些事情",
          "slug": "js-的-new-操作符做了哪些事情"
        },
        {
          "level": 2,
          "title": "JS 的各种位置",
          "slug": "js-的各种位置"
        },
        {
          "level": 2,
          "title": "Ajax 解决浏览器缓存问题",
          "slug": "ajax-解决浏览器缓存问题"
        },
        {
          "level": 2,
          "title": "JS 的防抖和节流",
          "slug": "js-的防抖和节流"
        },
        {
          "level": 2,
          "title": "垃圾回收机制",
          "slug": "垃圾回收机制"
        },
        {
          "level": 2,
          "title": "eval 是做什么的",
          "slug": "eval-是做什么的"
        },
        {
          "level": 2,
          "title": "理解前端模块化",
          "slug": "理解前端模块化"
        },
        {
          "level": 3,
          "title": "CommonJS、AMD",
          "slug": "commonjs、amd"
        },
        {
          "level": 2,
          "title": "对象深度克隆的简单实现",
          "slug": "对象深度克隆的简单实现"
        },
        {
          "level": 2,
          "title": "实现一个 once 函数，传入函数参数只执行一次",
          "slug": "实现一个-once-函数-传入函数参数只执行一次"
        },
        {
          "level": 2,
          "title": "将原生的 ajax 封装成 promise",
          "slug": "将原生的-ajax-封装成-promise"
        },
        {
          "level": 2,
          "title": "JS 监听对象属性的改变",
          "slug": "js-监听对象属性的改变"
        },
        {
          "level": 2,
          "title": "实现一个私有变量，用 getName 方法可以访问，不能直接访问",
          "slug": "实现一个私有变量-用-getname-方法可以访问-不能直接访问"
        },
        {
          "level": 2,
          "title": "== 和 ===、以及 Object.is 的区别",
          "slug": "和-、以及-object-is-的区别"
        },
        {
          "level": 2,
          "title": "setTimeout、setInterval 和 requestAnimationFrame",
          "slug": "settimeout、setinterval-和-requestanimationframe"
        },
        {
          "level": 2,
          "title": "如何实现 sleep 的效果",
          "slug": "如何实现-sleep-的效果"
        },
        {
          "level": 2,
          "title": "简单的实现一个 promise",
          "slug": "简单的实现一个-promise"
        },
        {
          "level": 2,
          "title": "Function._proto_(getPrototypeOf)是什么",
          "slug": "function-proto-getprototypeof-是什么"
        },
        {
          "level": 2,
          "title": "数组去重",
          "slug": "数组去重"
        },
        {
          "level": 2,
          "title": "事件代理在捕获阶段的实际应用",
          "slug": "事件代理在捕获阶段的实际应用"
        },
        {
          "level": 2,
          "title": "去除字符串首尾空格",
          "slug": "去除字符串首尾空格"
        },
        {
          "level": 2,
          "title": "性能优化",
          "slug": "性能优化"
        },
        {
          "level": 2,
          "title": "为什么要用闭包",
          "slug": "为什么要用闭包"
        },
        {
          "level": 2,
          "title": "JS 的语言特性",
          "slug": "js-的语言特性"
        },
        {
          "level": 2,
          "title": "如何判断一个数组",
          "slug": "如何判断一个数组"
        },
        {
          "level": 2,
          "title": "JS 实现跨域",
          "slug": "js-实现跨域"
        },
        {
          "level": 3,
          "title": "跨域原理",
          "slug": "跨域原理"
        },
        {
          "level": 2,
          "title": "重排和重绘",
          "slug": "重排和重绘"
        },
        {
          "level": 2,
          "title": "暂时性死区",
          "slug": "暂时性死区"
        },
        {
          "level": 2,
          "title": "Virtual DOM",
          "slug": "virtual-dom"
        },
        {
          "level": 2,
          "title": "webpack 用来干什么的",
          "slug": "webpack-用来干什么的"
        },
        {
          "level": 2,
          "title": "JS 中继承实现的几种方式",
          "slug": "js-中继承实现的几种方式"
        },
        {
          "level": 2,
          "title": "介绍一下 promise，及其底层如何实现",
          "slug": "介绍一下-promise-及其底层如何实现"
        }
      ]
    }
  ],
  "themeConfig": {
    "logo": "/Ming.jpg",
    "nav": [
      {
        "text": "JavaScript",
        "link": "/blog/javascript/基础"
      },
      {
        "text": "HTML+CSS",
        "items": [
          {
            "text": "HTML",
            "link": "/blog/basics/html"
          },
          {
            "text": "CSS",
            "link": "/blog/basics/css"
          }
        ]
      },
      {
        "text": "Vue",
        "link": "/blog/vue/基础"
      }
    ],
    "sidebar": {
      "/blog/basics/": [
        {
          "title": "HTML+CSS",
          "collapsable": false,
          "sidebarDepth": 2,
          "children": [
            {
              "title": "HTML",
              "path": "/blog/basics/html"
            },
            {
              "title": "CSS",
              "path": "/blog/basics/css"
            }
          ]
        }
      ],
      "/blog/javascript/": [
        {
          "title": "JavaScript",
          "collapsable": false,
          "sidebarDepth": 2,
          "children": [
            {
              "title": "基础",
              "path": "/blog/javascript/基础"
            },
            {
              "title": "问题",
              "path": "/blog/javascript/问题"
            }
          ]
        }
      ],
      "/blog/vue/": [
        {
          "title": "Vue",
          "collapsable": false,
          "sidebarDepth": 2,
          "children": [
            {
              "title": "基础",
              "path": "/blog/vue/基础"
            }
          ]
        }
      ]
    }
  }
}