/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "Ming's blog",
  "description": "记录所学知识",
  "base": "/MingBlog/",
  "headTags": [],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/home.jpg",
        "heroText": "Ming's Blog",
        "tagline": "Ming的学习簿",
        "actionText": "瞧一瞧",
        "actionLink": "/blog/basics/html/",
        "features": [
          {
            "title": "学习",
            "details": "学而不思则罔 | 思而不学则殆"
          },
          {
            "title": "记录",
            "details": "记录每一条知识，保存每一份收获"
          },
          {
            "title": "整理",
            "details": "学无止境，将所学的知识保留在这份笔记中"
          }
        ],
        "footer": "《劝学》不积跬步无以至千里"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-54afc71b",
      "path": "/"
    },
    {
      "title": "CSS",
      "frontmatter": {},
      "regularPath": "/blog/basics/css.html",
      "relativePath": "blog/basics/css.md",
      "key": "v-b8c4d480",
      "path": "/blog/basics/css.html",
      "headers": [
        {
          "level": 2,
          "title": "position 几个属性的作用",
          "slug": "position-几个属性的作用"
        },
        {
          "level": 2,
          "title": "px，em，rem 的区别",
          "slug": "px-em-rem-的区别"
        },
        {
          "level": 2,
          "title": "怎么让一个不定宽高的 DIV，垂直水平居中",
          "slug": "怎么让一个不定宽高的-div-垂直水平居中"
        },
        {
          "level": 2,
          "title": "CSS实现居中",
          "slug": "css实现居中"
        },
        {
          "level": 3,
          "title": "文字居中",
          "slug": "文字居中"
        },
        {
          "level": 3,
          "title": "图片居中",
          "slug": "图片居中"
        },
        {
          "level": 3,
          "title": "元素居中",
          "slug": "元素居中"
        },
        {
          "level": 2,
          "title": "Flex布局",
          "slug": "flex布局"
        },
        {
          "level": 2,
          "title": "BFC(Block formatting context)",
          "slug": "bfc-block-formatting-context"
        },
        {
          "level": 3,
          "title": "BFC的布局规则",
          "slug": "bfc的布局规则"
        },
        {
          "level": 3,
          "title": "如何创建BFC",
          "slug": "如何创建bfc"
        },
        {
          "level": 3,
          "title": "BFC的作用",
          "slug": "bfc的作用"
        },
        {
          "level": 2,
          "title": "CSS 权重",
          "slug": "css-权重"
        },
        {
          "level": 2,
          "title": "清除浮动的方式",
          "slug": "清除浮动的方式"
        },
        {
          "level": 2,
          "title": "渐进增强和优雅降级",
          "slug": "渐进增强和优雅降级"
        },
        {
          "level": 2,
          "title": "为什么利用多个域名来存储网站资源会更有效",
          "slug": "为什么利用多个域名来存储网站资源会更有效"
        },
        {
          "level": 2,
          "title": "网页的重绘与重排以及重构",
          "slug": "网页的重绘与重排以及重构"
        },
        {
          "level": 2,
          "title": "CSS3 新特性",
          "slug": "css3-新特性"
        },
        {
          "level": 3,
          "title": "CSS3 box-sizing",
          "slug": "css3-box-sizing"
        },
        {
          "level": 3,
          "title": "CSS Grid 网格布局教程",
          "slug": "css-grid-网格布局教程"
        },
        {
          "level": 2,
          "title": "伪类与伪元素",
          "slug": "伪类与伪元素"
        },
        {
          "level": 2,
          "title": "transition（过渡） transform（变换） animation（动画）",
          "slug": "transition-过渡-transform-变换-animation-动画"
        },
        {
          "level": 2,
          "title": "CSS 小细节",
          "slug": "css-小细节"
        },
        {
          "level": 3,
          "title": "CSS 引入的方式",
          "slug": "css-引入的方式"
        },
        {
          "level": 3,
          "title": "块元素和行元素",
          "slug": "块元素和行元素"
        },
        {
          "level": 3,
          "title": "文本省略号",
          "slug": "文本省略号"
        },
        {
          "level": 3,
          "title": "link 和 @import 的区别",
          "slug": "link-和-import-的区别"
        },
        {
          "level": 3,
          "title": "CSS Reset",
          "slug": "css-reset"
        },
        {
          "level": 3,
          "title": "Web 语义化",
          "slug": "web-语义化"
        },
        {
          "level": 3,
          "title": "inline ， block， inline-blockd的区别",
          "slug": "inline-block-inline-blockd的区别"
        },
        {
          "level": 3,
          "title": "display： none；与 visibility： hidden 的区别",
          "slug": "display-none-与-visibility-hidden-的区别"
        },
        {
          "level": 3,
          "title": "CSS Hack",
          "slug": "css-hack"
        },
        {
          "level": 3,
          "title": "overflow 属性值",
          "slug": "overflow-属性值"
        },
        {
          "level": 3,
          "title": "console 常用的方法",
          "slug": "console-常用的方法"
        },
        {
          "level": 3,
          "title": "rgba() 和 opacity 的区别",
          "slug": "rgba-和-opacity-的区别"
        },
        {
          "level": 3,
          "title": "Sass、LESS",
          "slug": "sass、less"
        },
        {
          "level": 3,
          "title": "行内元素、块级元素、空(void)元素、样式之间的转换",
          "slug": "行内元素、块级元素、空-void-元素、样式之间的转换"
        },
        {
          "level": 3,
          "title": "visibility=hidden, opacity=0，display:none",
          "slug": "visibility-hidden-opacity-0-display-none"
        },
        {
          "level": 3,
          "title": "隐藏页面中某个元素的几种方法",
          "slug": "隐藏页面中某个元素的几种方法"
        },
        {
          "level": 3,
          "title": "外边距折叠",
          "slug": "外边距折叠"
        },
        {
          "level": 3,
          "title": "float 的元素，display 是什么",
          "slug": "float-的元素-display-是什么"
        },
        {
          "level": 3,
          "title": "calc 属性",
          "slug": "calc-属性"
        },
        {
          "level": 3,
          "title": "display：table 和 <table>",
          "slug": "display-table-和-table"
        },
        {
          "level": 3,
          "title": "line-height 和 height 的区别",
          "slug": "line-height-和-height-的区别"
        },
        {
          "level": 3,
          "title": "如何不在本身上进行操作，改变一个 DOM 元素的字体颜色",
          "slug": "如何不在本身上进行操作-改变一个-dom-元素的字体颜色"
        },
        {
          "level": 3,
          "title": "设置一个元素的背景颜色，背景颜色会填充哪些区域",
          "slug": "设置一个元素的背景颜色-背景颜色会填充哪些区域"
        }
      ]
    },
    {
      "title": "HTML",
      "frontmatter": {},
      "regularPath": "/blog/basics/html.html",
      "relativePath": "blog/basics/html.md",
      "key": "v-d7b0c048",
      "path": "/blog/basics/html.html",
      "headers": [
        {
          "level": 2,
          "title": "浏览器标准模式和怪异模式",
          "slug": "浏览器标准模式和怪异模式"
        },
        {
          "level": 3,
          "title": "怪异模式",
          "slug": "怪异模式"
        },
        {
          "level": 3,
          "title": "标准模式",
          "slug": "标准模式"
        },
        {
          "level": 2,
          "title": "Doctype 作用",
          "slug": "doctype-作用"
        },
        {
          "level": 2,
          "title": "Label标签",
          "slug": "label标签"
        },
        {
          "level": 3,
          "title": "作用",
          "slug": "作用"
        },
        {
          "level": 3,
          "title": "用法",
          "slug": "用法"
        },
        {
          "level": 2,
          "title": "iframe 是什么、有什么缺点",
          "slug": "iframe-是什么、有什么缺点"
        },
        {
          "level": 2,
          "title": "src 与 href 的区别",
          "slug": "src-与-href-的区别"
        },
        {
          "level": 2,
          "title": "img标签上的title和alt属性的区别",
          "slug": "img标签上的title和alt属性的区别"
        },
        {
          "level": 2,
          "title": "前端页面的三层结构",
          "slug": "前端页面的三层结构"
        },
        {
          "level": 2,
          "title": "div+css 的布局较 table 布局有什么优点",
          "slug": "div-css-的布局较-table-布局有什么优点"
        },
        {
          "level": 2,
          "title": "Canvas 和 SVG 的区别",
          "slug": "canvas-和-svg-的区别"
        },
        {
          "level": 2,
          "title": "viewport",
          "slug": "viewport"
        },
        {
          "level": 3,
          "title": "viewport属性值",
          "slug": "viewport属性值"
        },
        {
          "level": 2,
          "title": "建议 CSS 的<link>标签放在<head>标签之间",
          "slug": "建议-css-的-link-标签放在-head-标签之间"
        },
        {
          "level": 2,
          "title": "建议 JS 的<script>标签放在</body>标签之前",
          "slug": "建议-js-的-script-标签放在-body-标签之前"
        },
        {
          "level": 2,
          "title": "渐进式渲染（progressive rendering）",
          "slug": "渐进式渲染-progressive-rendering"
        },
        {
          "level": 2,
          "title": "DOM 和 BOM",
          "slug": "dom-和-bom"
        },
        {
          "level": 2,
          "title": "DOM Tree 的构建",
          "slug": "dom-tree-的构建"
        },
        {
          "level": 2,
          "title": "前端需要注意的 SEO （搜索引擎优化）",
          "slug": "前端需要注意的-seo-搜索引擎优化"
        },
        {
          "level": 2,
          "title": "浏览器内核的理解",
          "slug": "浏览器内核的理解"
        },
        {
          "level": 2,
          "title": "attribute 和 property 的区别",
          "slug": "attribute-和-property-的区别"
        },
        {
          "level": 2,
          "title": "async 和 defer 的作用和区别",
          "slug": "async-和-defer-的作用和区别"
        },
        {
          "level": 2,
          "title": "image 和 canvas 在处理图片的区别",
          "slug": "image-和-canvas-在处理图片的区别"
        },
        {
          "level": 2,
          "title": "HTML5",
          "slug": "html5"
        },
        {
          "level": 3,
          "title": "HTML5 新特性",
          "slug": "html5-新特性"
        },
        {
          "level": 3,
          "title": "新增的操作 DOM 的方法",
          "slug": "新增的操作-dom-的方法"
        },
        {
          "level": 3,
          "title": "HTML5 本地存储概念",
          "slug": "html5-本地存储概念"
        },
        {
          "level": 3,
          "title": "什么是 Web Worker",
          "slug": "什么是-web-worker"
        },
        {
          "level": 3,
          "title": "HTML5 应用程序缓存和浏览器缓存有什么区别",
          "slug": "html5-应用程序缓存和浏览器缓存有什么区别"
        }
      ]
    },
    {
      "title": "JS",
      "frontmatter": {},
      "regularPath": "/blog/javascript/%E5%9F%BA%E7%A1%80.html",
      "relativePath": "blog/javascript/基础.md",
      "key": "v-feba9738",
      "path": "/blog/javascript/%E5%9F%BA%E7%A1%80.html",
      "headers": [
        {
          "level": 2,
          "title": "<script>",
          "slug": "script"
        },
        {
          "level": 3,
          "title": "推迟执行脚本",
          "slug": "推迟执行脚本"
        },
        {
          "level": 3,
          "title": "异步执行脚本",
          "slug": "异步执行脚本"
        },
        {
          "level": 3,
          "title": "动态加载脚本",
          "slug": "动态加载脚本"
        },
        {
          "level": 2,
          "title": "var 声明提升、let 关键字、const 关键字",
          "slug": "var-声明提升、let-关键字、const-关键字"
        },
        {
          "level": 2,
          "title": "数据类型",
          "slug": "数据类型"
        },
        {
          "level": 2,
          "title": "typeof 与 instanceof 区别",
          "slug": "typeof-与-instanceof-区别"
        },
        {
          "level": 2,
          "title": "for in、for of",
          "slug": "for-in、for-of"
        },
        {
          "level": 2,
          "title": "函数传递参数",
          "slug": "函数传递参数"
        },
        {
          "level": 2,
          "title": "执行上下文",
          "slug": "执行上下文"
        },
        {
          "level": 2,
          "title": "标识符查找",
          "slug": "标识符查找"
        },
        {
          "level": 2,
          "title": "原始值包装类型",
          "slug": "原始值包装类型"
        },
        {
          "level": 2,
          "title": "string 常用方法",
          "slug": "string-常用方法"
        },
        {
          "level": 3,
          "title": "slice()、substring()、substr()",
          "slug": "slice-、substring-、substr"
        },
        {
          "level": 3,
          "title": "indexOf()、lastIndexOf()",
          "slug": "indexof-、lastindexof"
        },
        {
          "level": 3,
          "title": "startsWith()、endsWith()、includes()",
          "slug": "startswith-、endswith-、includes"
        },
        {
          "level": 3,
          "title": "trim()",
          "slug": "trim"
        },
        {
          "level": 3,
          "title": "字符串解构",
          "slug": "字符串解构"
        },
        {
          "level": 3,
          "title": "toLowerCase()、toUpperCase()",
          "slug": "tolowercase-、touppercase"
        },
        {
          "level": 3,
          "title": "replace()",
          "slug": "replace"
        },
        {
          "level": 3,
          "title": "split()",
          "slug": "split"
        },
        {
          "level": 2,
          "title": "Math",
          "slug": "math"
        },
        {
          "level": 2,
          "title": "Array 常用方法",
          "slug": "array-常用方法"
        },
        {
          "level": 3,
          "title": "valueOf()",
          "slug": "valueof"
        },
        {
          "level": 3,
          "title": "join()",
          "slug": "join"
        },
        {
          "level": 3,
          "title": "栈方法 push()、pop()",
          "slug": "栈方法-push-、pop"
        },
        {
          "level": 3,
          "title": "队列方法 shift()、unshift()",
          "slug": "队列方法-shift-、unshift"
        },
        {
          "level": 3,
          "title": "排序方法 reverse()、sort()",
          "slug": "排序方法-reverse-、sort"
        },
        {
          "level": 3,
          "title": "concat()",
          "slug": "concat"
        },
        {
          "level": 3,
          "title": "slice()",
          "slug": "slice"
        },
        {
          "level": 3,
          "title": "splice()",
          "slug": "splice"
        },
        {
          "level": 3,
          "title": "indexOf()、lastIndexOf()和 includes()",
          "slug": "indexof-、lastindexof-和-includes"
        },
        {
          "level": 3,
          "title": "find()、findIndex()",
          "slug": "find-、findindex"
        },
        {
          "level": 3,
          "title": "迭代方法 every()、filter()、forEach()、map() 和 some()",
          "slug": "迭代方法-every-、filter-、foreach-、map-和-some"
        },
        {
          "level": 3,
          "title": "归并方法 reduce()、reduceRight()",
          "slug": "归并方法-reduce-、reduceright"
        }
      ]
    },
    {
      "title": "问题",
      "frontmatter": {},
      "regularPath": "/blog/javascript/%E9%97%AE%E9%A2%98.html",
      "relativePath": "blog/javascript/问题.md",
      "key": "v-4ee5ef60",
      "path": "/blog/javascript/%E9%97%AE%E9%A2%98.html"
    }
  ],
  "themeConfig": {
    "logo": "/Ming.jpg",
    "nav": [
      {
        "text": "HTML+CSS",
        "items": [
          {
            "text": "HTML",
            "link": "/blog/basics/html"
          },
          {
            "text": "CSS",
            "link": "/blog/basics/css"
          }
        ]
      },
      {
        "text": "JavaScript",
        "link": "/blog/javascript/基础"
      },
      {
        "text": "Vue",
        "link": "https://baidu.com"
      }
    ],
    "sidebar": {
      "/blog/basics/": [
        {
          "title": "HTML+CSS",
          "collapsable": false,
          "sidebarDepth": 2,
          "children": [
            {
              "title": "HTML",
              "path": "/blog/basics/html"
            },
            {
              "title": "CSS",
              "path": "/blog/basics/css"
            }
          ]
        }
      ],
      "/blog/javascript/": [
        {
          "title": "JavaScript",
          "collapsable": false,
          "sidebarDepth": 2,
          "children": [
            {
              "title": "基础",
              "path": "/blog/javascript/基础"
            },
            {
              "title": "问题",
              "path": "/blog/javascript/问题"
            }
          ]
        }
      ]
    }
  }
}